name: CI/CD for Call Center Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/call_center_back"

      - name: Restart Docker container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/call_center_back
            # Проверяем наличие .env файла
            if [ -f .env ]; then echo ".env файл найден"; else echo "Ошибка: .env не найден!"; exit 1; fi
            
            # Остановка старого контейнера
            docker stop call_center_container || true
            docker rm call_center_container || true
            
            # Сборка нового образа
            docker build -t call_center_back .
            
            # Запуск контейнера с .env
            docker run -d --env-file .env -p 5000:5000 --name call_center_container call_center_back
