name: CI/CD for Call Center Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/call_center_back"

      - name: Restart Docker container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/call_center_back
            
            # Обновляем репозиторий
            git pull origin main

            # Проверяем изменения в requirements.txt
            if git diff --name-only HEAD HEAD~1 | grep -q 'requirements.txt'; then
              echo "requirements.txt изменён. Пересобираем контейнер."
              
              # Остановка старого контейнера
              docker stop call_center_container || true
              docker rm call_center_container || true

              # Сборка нового образа
              docker build -t call_center_back .

              # Запуск контейнера с .env
              docker run -d --env-file .env -p 5000:5000 --name call_center_container call_center_back
            else
              echo "Только код изменён. Перезапуск контейнера."
              
              # Перезапуск контейнера без пересборки
              docker stop call_center_container || true
              docker rm call_center_container || true
              docker run -d --env-file .env -p 5000:5000 --name call_center_container call_center_back
            fi