name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy backend files via SSH
      run: scp -r * root@212.113.102.14:/var/www/call_center_back

    - name: Clone and copy frontend repository
      run: |
        git clone https://girudomed.kazan%40gmail.com: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@github.com/girudomed/call_center_front.git
        scp -r call_center_front/* root@212.113.102.14:/var/www/call_center_front

    - name: Execute deployment script
      run: ssh root@212.113.102.14 'bash -s' < /var/www/call_center_back/deploy.sh
