name: CI/CD for Call Center Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "=== Проверяем наличие проекта на сервере ==="
            if [ ! -d ~/call_center_back ]; then
              echo "Репозиторий не найден. Клонируем заново..."
              git clone https://github.com/girudomed/call_center_back.git ~/call_center_back
            fi

            cd ~/call_center_back

            echo "=== Обновляем репозиторий ==="
            git fetch origin
            git reset --hard origin/main

            echo "=== Принудительно удаляем существующий контейнер ==="
            docker stop call_center_container || true
            docker rm call_center_container || true

            echo "=== Перезапускаем контейнеры через docker-compose ==="
            docker-compose down || true
            docker-compose up --build -d

            echo "=== Очистка старых Docker-ресурсов ==="
            docker image prune -af || true
            docker container prune -f || true

            echo "=== Деплой завершён успешно ==="